CREATE TABLE Users (
	Id BIGINT IDENTITY NOT NULL,
	Username VARCHAR(30) UNIQUE NOT NULL,
	Password VARCHAR(26) NOT NULL,
	ProfilePicture VARBINARY(MAX),
	LastLoginTime DATETIME,
	IsDeleted BIT,
	CONSTRAINT PK_Users PRIMARY KEY (Id)
)

ALTER TABLE Users
ADD CONSTRAINT CK_ProfilePictureSize CHECK (DATALENGTH(ProfilePicture) <= 900 * 1024)

INSERT INTO Users
VALUES 
('Dimitar', '12345', NULL, NULL, 0),
('Ivan', '12346', NULL, NULL, 1),
('Petyr', '12347', NULL, NULL, 0),
('Ivaylo', '12348', NULL, NULL, 1),
('Georgi', '12349', NULL, NULL, 0)